#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global

    if [ -f "$HOME/.Brewfile.local" ]; then 
      echo "Updating context-specific Homebrew bundle"
      brew bundle --global --file=".Brewfile.local"
    fi
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

fi

if [ -f "$HOME/.zshenv.local" ]; then 
  cat .zshenv.local >> .zshenv
  rm .zshenv.local
fi