# Time
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_12HR=true

# Battery
SPACESHIP_BATTERY_SHOW=always
SPACESHIP_BATTERY_SYMBOL_CHARGING=󰂄·
SPACESHIP_BATTERY_SYMBOL_FULL=󱟢·

# Golang
SPACESHIP_GOLANG_SYMBOL=·